---
name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true
        enable-cache: true
        cache-suffix: ${{ matrix.python-version }}
        python-version: ${{ matrix.python-version }}

    - name: Install project
      run: |
        uv pip install --editable='.[develop,test]'

    - name: Check code style
      if: matrix.python-version != '3.7' && matrix.python-version != 'pypy-3.7'
      run: |
        poe lint

    - name: Run software tests
      run: |
        poe test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
