---
name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests-all:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.15"
          - "3.15t"
          - "pypy3.11"

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
      with:
        activate-environment: true
        enable-cache: true
        cache-suffix: ${{ matrix.python-version }}
        python-version: ${{ matrix.python-version }}

    - name: Install project
      run: |
        uv pip install --editable='.[develop,test]'

    - name: Validate project
      run: |
        poe check

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true

  tests-legacy:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
        python-version:
          - "3.6"
          - "3.7"

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install Python
      uses: LizardByte/actions/actions/setup_python@2f67c4512b418fa42affd50e4f8aa456b687f1b8
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install project (Python 3.6)
      if: matrix.python-version == '3.6' || matrix.python-version == 'pypy-3.6'
      run: |
        # Python 3.6 does not understand `pyproject.toml` setups,
        # so install the requirements from dedicated file.
        pip install --requirement requirements-test.txt

    - name: Install project (Python 3.7+)
      if: matrix.python-version != '3.6' && matrix.python-version != 'pypy-3.6'
      run: |
        # `setuptools 0.64.0` adds support for editable install hooks (PEP 660).
        # https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6400
        pip install "setuptools>=64" --upgrade

        # Install package in editable mode.
        pip install --use-pep517 --prefer-binary --editable='.[develop,test]'

    - name: Run software tests
      run: |
        poe test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
